# Generated by Django 4.2.6 on 2023-11-10 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_remove_category_description_remove_product_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='desc',
            field=models.CharField(max_length=80, null=True),
        ),
    ]
