# Generated by Django 4.2.7 on 2023-11-14 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_product_category_product_createdtime_product_desc_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('desc', models.CharField(max_length=80, null=True)),
                ('products', models.TextField()),
                ('price', models.FloatField(null=True)),
            ],
        ),
    ]
