# Generated by Django 4.2.7 on 2023-11-14 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_receipt_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receipt',
            name='desc',
        ),
    ]
